data = '''
[
		{name: '"Овчаренко', 'surname': 'Павел', 'patronymic': 'Николаевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '2'}, 
		{name: '"Коблов', 'surname': 'Кузьма', 'patronymic': '"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '3'}, 
		{name: '"Соложенков', 'surname': 'Георгий', 'patronymic': 'Васильевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '4'}, 
		{name: '"Тарасова', 'surname': 'Маргарита', 'patronymic': 'Викторовна"', 'location': '"48.7792833 132.8625016"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '5'}, 
		{name: '"Кондратьев', 'surname': 'Иван', 'patronymic': '"', 'location': '"48.7792833 132.8625016"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '6'}, 
		{name: '"Ширяев', 'surname': 'Иван', 'patronymic': 'Иванович"', 'location': '"51.4753593 46.0897162"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '7'}, 
		{name: '"Туберозов', 'surname': 'Никалай', 'patronymic': 'Ленинград)"', 'location': '"59.939226 29.534304"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '8'}, 
		{name: '"Семенов', 'surname': 'Иван', 'patronymic': 'Иванович"', 'location': '"55.5815245 36.8251381"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '9'}, 
		{name: '"Севрюгин', 'surname': 'Дмитрий', 'patronymic': 'Иванович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '10'}, 
		{name: '"Анучин', 'surname': 'Максим', 'patronymic': 'Яковлевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '11'}, 
		{name: '"Блынский', 'surname': 'Яков', 'patronymic': 'Васильевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '12'}, 
		{name: '"Степченков', 'surname': 'Михаил', 'patronymic': 'Константинович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '13'}       , 
		{name: '"Литышев', 'surname': 'Павел', 'patronymic': 'Петрович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '14'}, 
		{name: '"Семенов', 'surname': 'Александр', 'patronymic': 'Иванович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '15'}, 
		{name: '"Иньков', 'surname': 'Павел', 'patronymic': 'Григорьевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '16'}, 
		{name: '"Борисов', 'surname': 'Семен', 'patronymic': 'Георгиевич"', 'location': '"49.327553 42.0594664"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '17'}, 
		{name: '"Дьяконов', 'surname': 'Сергей', 'patronymic': 'Степанович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '18'}, 
		{name: '"Макарова', 'surname': 'Зоя', 'patronymic': 'Николаевна"', 'location': '"55.1481091 59.6226577"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '20'}, 
		{name: '"Киракосян', 'surname': 'Шапахак', 'patronymic': '(26.06.1941-21.031995)"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '21'}, 
		{name: '"Пахомов', 'surname': 'Александр', 'patronymic': 'Егорович"', 'location': '"55.7539333 37.6186063"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '22'}, 
		{name: '"Блохин', 'surname': 'Трофим', 'patronymic': 'Дмитриевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '23'}, 
		{name: '"Орлов', 'surname': 'Виктор', 'patronymic': 'Александрович"', 'location': '"43.0293616 44.5916733"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '24'}, 
		{name: '"Клюкало', 'surname': 'Николай', 'patronymic': 'Александрович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '25'}, 
		{name: '"Адикаев', 'surname': 'Фатих', 'patronymic': 'Саддыкович"', 'location': '"54.2937181 44.9614606"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '26'}, 
		{name: '"Мои', 'surname': 'деды', 'patronymic': 'Николаевич', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '27'}, 
		{name: '"Мамаев', 'surname': 'Михаил', 'patronymic': '"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '28'}, 
		{name: '"Шерер', 'surname': 'Галина', 'patronymic': 'Михайловна"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '29'}, 
		{name: '"Панферов', 'surname': 'Аким', 'patronymic': 'Яковлевич', 'location': '"53.4904639 40.4852227"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '30'}, 
		{name: '"Щеголев', 'surname': 'Иван', 'patronymic': 'Викторович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '31'}, 
		{name: '"Сысоев', 'surname': 'Алексей', 'patronymic': 'Владимирович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '32'}, 
		{name: '"Айвазян', 'surname': 'Сурен', 'patronymic': 'Алексеевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '33'}, 
		{name: '"Токарев', 'surname': 'Николай', 'patronymic': 'Дмитриевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '34'}, 
		{name: '"Петров', 'surname': 'Константин', 'patronymic': 'Ефимович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '35'}, 
		{name: '"Бойко', 'surname': 'Егор', 'patronymic': 'Игнатьевич"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '36'}, 
		{name: '"Вербицкий', 'surname': 'Пётр', 'patronymic': 'Андреевич"', 'location': '"44.9442637 42.1594563"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '37'}, 
		{name: '"Никулин', 'surname': 'Михаил"', 'patronymic': 'Михаил"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '38'}, 
		{name: '"Муркин', 'surname': 'Алексей', 'patronymic': 'Иванович"', 'location': '"55.7024151 78.1737926"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '39'}, 
		{name: '"Парунакян', 'surname': 'Альфред', 'patronymic': 'Левонович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '40'}, 
		{name: '"Ващилов', 'surname': 'Александр', 'patronymic': 'Павлович"', 'location': '', 'img_url': './src/photo.jpg', 'visible': True, 'id': '41'}, 
		{name: '"Дунаевский', 'surname': 'Константин', 'patronymic': 'Дмитриевич"', 'location': '"45.1856351 78.0016422"', 'img_url': './src/photo.jpg', 'visible': True, 'id': '42'}
		]
'''

print(data.replace("'surname'", "surname").replace("'patronymic'", "patronymic").replace("'location'", "location").replace("'img_url'", "img_url").replace("'visible'", "visible").replace("'id'", "id").replace('"', ''))